### ISSUE TITLE
 Staging failed: Buildpack compilation step failed : No such file or directory - /home/vcap/tmp/httpd-2.4.20.tar.gz 

### ISSUE THREAD

**Issue by ZiedZinelabidine** [cloudfoundry/cf-release#1003]
My cloudfoundry didn't find the folder:

```
No such file or directory - /home/vcap/tmp/httpd-2.4.20.tar.gz
```

I use php_buildpack-cached-v4.3.14.zip.  My manifest: 

```
applications:
- name: portail-zzinelabidine
  memory: 1028M
  disk_quota: 1028M
  instances: 1
  host: portail-zzinelabidine
  path: .
  buildpack: php_buildpack_4_3_14 
  env:
    ENV_TYPE: DEV
    BP_DEBUG: false
    OPF_LOG_HANDLER : Locallog
```

options.json :+1: 

```
{
"WEB_SERVER" :"httpd" ,
"HTTPD_VERSION": "2.4.20",
"HTTPD_PACKAGE": "httpd-{HTTPD_VERSION}.tar.gz",
"HTTPD_DOWNLOAD_URL": "/httpd/{HTTPD_VERSION}/{HTTPD_PACKAGE}",
"HTTPD_STRIP": true,
"WEBDIR": "src/var/www/server",
"LIBDIR": "src/lib",
"PHP_MODULES":["fpm", "cli","cgi", "pear", "npm","php-composer-semver","common" ,"gd","soap", "common" , "json"] ,
"PHP_EXTENSIONS": [ "openssl","bz2", "zlib", "curl","mbstring","redis","mcrypt"]
}
```

httpd.conf :+1: 

```
ServerRoot "${HOME}/httpd"
Listen ${PORT}
ServerAdmin "${HTTPD_SERVER_ADMIN}"
ServerName "0.0.0.0"
DocumentRoot "${HOME}/#{WEBDIR}"
Include extra/httpd-modules.conf
Include extra/httpd-directories.conf
Include extra/httpd-mime.conf
Include extra/httpd-logging.conf
Include extra/httpd-mpm.conf
Include extra/httpd-default.conf
Include extra/httpd-remoteip.conf
Include extra/httpd-php.conf
Include extra/httpd-deflate.conf
#Other directives


RewriteEngine On
RewriteCond %{REQUEST_URI} ^/version\.php [OR]
RewriteCond %{REQUEST_URI} ^/shooter.*\.php
RewriteRule ^/(.*)$ fcgi://127.0.0.1:9000${HOME}/#{WEBDIR}/$1 [P]
                                                 
RewriteCond %{REQUEST_URI} !^/favicon.ico
RewriteRule ^(.*)$  fcgi://127.0.0.1:9000${HOME}/#{WEBDIR}/index.php$1 [P]
```
