### ISSUE TITLE
consul_agent  in api_z1 missing for OpenStack in docs 

### ISSUE THREAD

**Issue by shijiaxin** [cloudfoundry/cf-release#1012]
```
- name: api_z1
    templates:
      - name: go-buildpack
        release: cf
      - name: binary-buildpack
        release: cf
      ... ...
```
it seems the following two lines are missing, and api_z1 will fail to find blobstore since the endpoint is  https://blobstore.service.cf.internal
```
      - name: consul_agent
        release: cf
```

**Comment by Infra-Red** [comment]
And also java-buildpack packages are missing on the Openstack stub, without the packages acceptance tests will fail:
```
- name: api_z1
    templates:
    - name: java-buildpack
      release: cf
    - name: java-offline-buildpack
       release: cf    
```
