### ISSUE TITLE
More instances of postgresQl for uaadb and ccdb

### ISSUE THREAD

**Issue by rahul221191** [cloudfoundry/cf-release#1088]
Can we have two instances of  the postgres for UAADB and CCDB on two different network?
If yes what changes we need to to do in our stub file.
i am posting my first  instance 
this in my cf-stub.yml file for postgres

```
- name: postgres_z1
  instances: 1
  networks:
- name: network1
  static_ips: (( static_ips(7) ))
```

```
databases:
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: sdadasdasdasdasdasdasdas
      - tag: admin
        name: uaaadmin
        password: sdasdasdasdasdsasdasdasdsa
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true
  cc:
    <<: (( merge ))
    default_to_diego_backend: true
    staging_upload_user: staging_upload
    staging_upload_password: dsadasdasdasdasdasdsa
    bulk_api_password: sdadasdasdasdasdasdasdasdsadasds
    db_encryption_key: sdasdasdasdasdasdasdasdasdasdasdsa
    allow_app_ssh_access: true
  ccdb:
    db_scheme: postgres
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: sdasdasdasdasdasdsadivciUmt9
    databases:
      - tag: cc
        name: ccdb
        citext: true
  uaadb:
    db_scheme: postgresql
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: dsadasdasdasdsads
    databases:
      - tag: uaa
        name: uaadb
        citext: true
```
can you please help me out with that.
thanks in advance

**Comment by dsabeti** [comment]
Hi @rahul221191 

I think it could maybe work, but I'm not sure it's a good idea. As far as I know, the `postgres` job was never intended to be anything but a singleton. Maybe @valeriap can chime in on this?

Also, the manifest generation scripts seem to require a single-node postgres, so if you do this, you wouldn't be able to use those scripts.

But, if you really want to try it, you'd have to have the two postgres nodes running as separate jobs:
```
jobs:
- name: postgres_z1
  networks:
  - name: network1
  properties:
    databases:
      address: IP_1
- name: postgres_z2
  networks:
  - name: network2
  properties:
    databases:
      address: IP_2
```
You have to do this because the two nodes will have different addresses (IP / domain), but there is only one property to house that value. (For what it's worth, this clearly indicated that the postgres job was always meant to be a singleton.)

Hope this helps,
David
