### ISSUE TITLE
"client id must be unique error" while updating service broker

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/cf-release#1092]
Since cf release 245 , while updating service broker whose catalog contains entry for [dashboard client](http://docs.cloudfoundry.org/services/dashboard-sso.html#registering-dashboard-client) , I get a Server error :

```
$ cf update-service-broker p-mysql <USER> <PASSWORD> <PORT>

Server error, status code: 502, error code: 270012, message: Service broker catalog is invalid:
Service p-mysql
  Service dashboard client id must be unique
```

Here is my cloudFoundry manifest snippet 

```
  cc-service-dashboards:
        authorities: clients.read,clients.write,clients.admin
        authorized-grant-types: authorization_code,client_credentials
        scope: openid,cloud_controller_service_permissions.read
        secret: UAA-CLIENT-CC-SERVICE-DASHBOARD-vavceztUvyipNisviov3
```

Any thoughts about what is going on ?
Is there a config to disable dashdoard auto registration ?

Cheers
