### ISSUE TITLE
Adding OAuth to deployment

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/cf-release#1135]
Hi,
I tried to enable OAuth login on a deployment:

```yaml
  uaa:
    login:
      oauth:
        providers:
          federation:
            type: oauth2.0
            authUrl: ***
            tokenUrl: ***
            issuer: ***
            redirectUrl: ***
            scopes:
              - openid
              - email
              - profile
            linkText: Login with OAuth
            showLinkText: true
            addShadowUserOnLogin: true
            skipSslValidation: false
            attributeMappings:
              user_name: email
```

The section is included in the final deployment file, but there are no changes on the UAA side. Is this feature currently not enabled, or why does it not get applied?
