### ISSUE TITLE
Cannot have more than 5 rules in a warden security group

### ISSUE THREAD

**Issue by teancom** [cloudfoundry/cf-release#611]
We are currently overriding the `public_networks` security group in our spiff templates, using `meta.default_security_group_definitions`. What I have discovered is that if we put in more than 5 rules into the security group, anything past the fifth is silently dropped. I verified that order doesn't matter (it's always the sixth rule onward), and ruled out any sort of weirdness in terms of line-endings or bad characters in the config file.

To reproduce, you can use the following test rules:

```yaml
meta:
  default_security_group_definitions:
  - name: public_networks
    rules:
     - protocol: all
       destination: 0.0.0.0-0.255.255.255
     - protocol: all
       destination: 1.0.0.0-1.255.255.255
     - protocol: all
       destination: 2.0.0.0-2.255.255.255
     - protocol: all
       destination: 3.0.0.0-3.255.255.255
     - protocol: all
       destination: 4.0.0.0-4.255.255.255
     - protocol: all
       destination: 5.0.0.0-5.255.255.255
     - protocol: all
       destination: 6.0.0.0-6.255.255.255
```

Output when running `bosh deploy`:
```
Properties
cc
  ± security_group_definitions:
    - {"name"=>"public_networks", "rules"=>[{"destination"=>"0.0.0.0-9.255.255.255", "protocol"=>"all"}, {"destination"=>"11.0.0.0-169.253.255.255", "protocol"=>"all"}, {"destination"=>"169.255.0.0-172.15.255.255", "protocol"=>"all"}, {"destination"=>"172.32.0.0-192.167.255.255", "protocol"=>"all"}, {"destination"=>"192.169.0.0-255.255.255.255", "protocol"=>"all"}]}
    + {"name"=>"public_networks", "rules"=>[{"destination"=>"0.0.0.0-0.255.255.255", "protocol"=>"all"}, {"destination"=>"1.0.0.0-1.255.255.255", "protocol"=>"all"}, {"destination"=>"2.0.0.0-2.255.255.255", "protocol"=>"all"}, {"destination"=>"3.0.0.0-3.255.255.255", "protocol"=>"all"}, {"destination"=>"4.0.0.0-4.255.255.255", "protocol"=>"all"}]}
```

Expected output when running `bosh deploy`:
```
Properties
cc
  ± security_group_definitions:
    - {"name"=>"public_networks", "rules"=>[{"destination"=>"0.0.0.0-9.255.255.255", "protocol"=>"all"}, {"destination"=>"11.0.0.0-169.253.255.255", "protocol"=>"all"}, {"destination"=>"169.255.0.0-172.15.255.255", "protocol"=>"all"}, {"destination"=>"172.32.0.0-192.167.255.255", "protocol"=>"all"}, {"destination"=>"192.169.0.0-255.255.255.255", "protocol"=>"all"}]}
    + {"name"=>"public_networks", "rules"=>[{"destination"=>"0.0.0.0-0.255.255.255", "protocol"=>"all"}, {"destination"=>"1.0.0.0-1.255.255.255", "protocol"=>"all"}, {"destination"=>"2.0.0.0-2.255.255.255", "protocol"=>"all"}, {"destination"=>"3.0.0.0-3.255.255.255", "protocol"=>"all"}, {"destination"=>"4.0.0.0-4.255.255.255", "protocol"=>"all"},{"destination"=>"5.0.0.0-5.255.255.255", "protocol"=>"all"},{"destination"=>"6.0.0.0-6.255.255.255", "protocol"=>"all"}]}
```

This is using cf release v196, commit hash 3dbb4d00. Let me know if any additional information is needed.

Thanks!

**Comment by luan** [comment]
Hi @teancom,

You're correct, that doesn't work, by design spiff won't merge arrays like that. What we suggest is override the property itself on the `cc` section, like we do [here](https://github.com/cloudfoundry/cf-release/blob/develop/bosh-lite/cf-stub-spiff.yml#L12-L42).

A simple example of how spiff does this:

**`template.yml`**:
```yml
meta:
  a: 1
  b: (( merge ))
  c: [1,2,3]
```

**`stub.yml`**:
```yml
meta:
  b: 2
  c: [4,5,6,7]
```

```bash
 spiff merge template.yml stub.yml > result..yml
```

**`result.yml`**:
```yml
meta:
  a: 1
  b: 2
  c:
  - 1
  - 2
  - 3
```

Let us know if that helps.

Thanks,
@luan & @sujoybasu, CF Runtime Team
