### ISSUE TITLE
stemcell and version variable for spiff

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/cf-release#889]
shouldn't the stemcell name and version be a variable for spiff?
in the templates?

example:
https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-infrastructure-openstack.yml#L9

**Comment by Amit-PivotalLabs** [comment]
@ramonskie yup, they are configurable:

https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-infrastructure-openstack.yml#L6-L10

In your stub, specify:

```
meta:
  stemcell:
    name: YOUR_STEMCELL_NAME
    version: YOUR_STEMCELL_VERSION
```
