### ISSUE TITLE
can't deploy cf-deployment

### ISSUE THREAD

**Issue by mamu-icc** [cloudfoundry/cf-release#914]
Hello there

I have some trouble deploying cf on openstack. Have followed the following tutorial:
https://docs.cloudfoundry.org/deploying/openstack/index.html
Everything except a few steps didnt work well.

1. When i deploy the envionment it says it needs the "cf2" network, which is not listed in the [template manifest of cf](https://docs.cloudfoundry.org/deploying/openstack/cf-stub.html), so i added it manually, copied just the cf1 and changed the values, it looks now like this:

```
networks:
  - name: floating
    type: vip
    cloud_properties:
      net_id: 61d93361-fd32-4db0-b28a-16cb057940c1
      security_groups: []
  - name: cf1
    type: manual
    subnets:
    - range: 10.10.13.0/24
      gateway: 10.10.13.1
      reserved:
      - 10.10.13.10 - 10.10.13.49
      - 10.10.13.101 - 10.10.13.200
      dns:
      - 8.8.8.8
      static:
      - 10.10.13.50 - 10.10.13.100
      cloud_properties:
        net_id: 61d93361-fd32-4db0-b28a-16cb057940c1
        security_groups: ["cf"]

  - name: cf2
    type: manual
    subnets:
    - range: 10.10.12.0/24
      gateway: 10.10.12.1
      reserved:
      - 10.10.12.10 - 10.10.12.49
      - 10.10.12.101 - 10.10.12.200
      dns:
      - 8.8.8.8
      static:
      - 10.10.12.50 - 10.10.12.100
      cloud_properties:
        net_id: 61d93361-fd32-4db0-b28a-16cb057940c1
        security_groups: ["cf"]

```

Now it doesn't complain about missing networks, but the build still fails.

I can see that bosh is trying to start vm's but they are not connected to the given network in the manifest. they are just "floating" around and deleting after a while because of no connection to the instance which makes completely sense in this case. 

I had the same problem with initializing bosh, but i could bypass the problem with a dynamic network configuration. 

I tried also to modify cf-manifest to deploy it with dynamic network, which will not work..

Do i miss something or do i have a wrong configuration?`Or is it maybe a bug in the templates?

Cheers, mamu
