### ISSUE TITLE
New blobstore properties are not optional

### ISSUE THREAD

**Issue by omazhary** [cloudfoundry/cf-release#941]
The blobstore properties introduced in v233 in the ```properties``` block are not optional. Meaning, you can't set the ```blobstore``` block to ```null``` by ```blobstore: null``` as shown in the [document](https://docs.google.com/document/d/1PDswakRCBdnQEbJYZa01Fo8vo3DC6h3rtP3sckcp5Eo/edit?pref=2&pli=1#heading=h.oi6irfqgers2) when keeping the existing nfs blobstore. The templates no longer function, and the deployment fails at the manifest creation stage.

This happens for each property that is left unchanged:
```
Error 100: Error filling in template `signer_ctl.sh.erb' for `nfs_z1/0' (line 23: Can't find property `["blobstore.secure_link.secret"]')
```

**Comment by youreddy** [comment]
Hello @omazhary, 

Are your `blobstore_z1` instances set to 0 in the deployment manifest file? This will ensure that the blobstore vm does not run and therefore not look for the unspecified properties.

@youreddy & @petergtz 
CF CAPI Team

**Comment by omazhary** [comment]
Yes. It has no instances. That's why I found it strange. I filled the properties up with the same defaults provided for warden deployments, and so far it works. However, it is not a pretty workaround.

This is my blobstore job section of the manifest:
```
- instances: 0
  name: blobstore_z1
  <other_properties_here>
```

**Comment by simonleung8** [comment]
Hello @omazhary 

`signer_ctl.sh.erb` is a control script for the webdav blobstore, and it shouldn't be executed during the nfs_z1 job, therefore, the nfs_z1 job might not be properly configured.

If you don't mind, you can post the jobs section of nfs_z1 in your manifest and we can help diagnose the problem. Be sure to exclude any sensitive information (password etc.). 

Thanks
Simon & @petergtz

**Comment by omazhary** [comment]
Of course, here it is:
```
- instances: 1
  name: nfs_z1
  networks:
  - name: cf1
    static_ips:
    - <blobstore_ip>
  persistent_disk: 102400
  properties:
    consul:
      agent:
        services:
          blobstore: {}
    metron_agent:
      zone: z1
    route_registrar:
      routes:
      - name: blobstore
        port: <blobstore_port>
        registration_interval: 20s
        tags:
          component: blobstore
        uris:
        - <blobstore_uri>
  resource_pool: medium_z1
  templates:
  - name: consul_agent
    release: cf
  - name: debian_nfs_server
    release: cf
  - name: metron_agent
    release: cf
  - name: blobstore
    release: cf
  - name: route_registrar
    release: cf
  update: {}
```
Could it be that the colocated ```blobstore``` job is actually meant for the WebDAV blobstore?
